stages:
- stage: 'Build'
  displayName: "Sample Job for CI"
  jobs:
  - job: 'CIjob'
    pool:
      name: 'Hosted VS2017'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line CI script'

- stage: 'Deploy'
  displayName: "Sample Job for CD"
  jobs:
  - deployment: 'CDJob'
    pool: 
      name: 'Hosted VS2017'
    environment: 'muthuk-emptyenv'
    strategy:
     runOnce:
      deploy:
        steps:
        - script: echo Hello, world!
        displayName: 'Run a one-line CD script'